 <!-- Start Left Side -->
        <div class="col-lg-4 aside-section">

          <!-- Search -->
          <div class="card search">
            <h3 class="card-header">Search</h3>
            <div class="card-block">

              <div class="input-group">
               <input type="text" class="form-control" placeholder="Search for...">
               <span class="input-group-btn">
                 <button class="btn btn-danger" type="button"><i class="fa fa-search"></i></button>
               </span>
             </div>

            </div>
          </div>


          <!-- Related Posts -->
          <div class="card ">
            <h3 class="card-header">Most Popular</h3>
            <div class="card-block">

            @for($i = 0; $i < 4; $i++)

              <div class="row post-wrap">
                  <div class="col-sm-4 col-md-2 col-lg-4 post-img">
                      <img src="{{ asset('assets/images/comment-img.jpg') }}" alt="">
                  </div>
                  <div class="col-sm-8 col-md-10 col-lg-8 post-title">
                      <a href="#"> Post title generated by users in our magazine </a>
                    <div class="aside-post-info">
                        <span>Sep 24, 2017</span> | <a href="#">Art</a>
                    </div>
                  </div>
              </div>
            @endfor
              


            </div>
          </div>
          <!-- Related Posts / End -->
          <!-- Ads  -->
          <div class="card ads-section">
            <h3 class="card-header">Advertisment</h3>
            <div class="card-block">
              <a href="#">
                <img src="assets/images/macdonald-ads.jpg" class="ads-img" alt="">
              </a>

            </div>
          </div>
          <!-- Ads / End -->

          <!-- Follow Us -->
          <div class="card follow-section">
            <h3 class="card-header">FOLLOW US</h3>
            <div class="card-block">

                <ul class="list-group">
                  <li class="list-group-item">
                    <a href="{{ getSettingByKey('facebook') }}">
                      <img src="assets/images/icons/facebook.png" alt="Facebook"> FACEBOOK
                    </a>
                  </li>
                  <li class="list-group-item">
                    <a href="{{ getSettingByKey('twitter') }}">
                      <img src="assets/images/icons/twitter.png" alt="Facebook"> TWITTER
                    </a>
                  </li>
                  <li class="list-group-item">
                    <a href="{{ getSettingByKey('google') }}">
                      <img src="assets/images/icons/google_plus.png" alt="Facebook"> GOOGLE
                    </a>
                  </li>
                  <li class="list-group-item">
                    <a href="{{ getSettingByKey('youtube') }}">
                      <img src="assets/images/icons/youtube.png" alt="Facebook"> YOUTUBE
                    </a>
                  </li>
                </ul>

            </div>
          </div>

        </div> <!-- Sidebar / End -->